### ISSUE TITLE
When admin wants to delete a comment of a post

### ISSUE THREAD

**Issue by shahryarjb** [shahryarjb/mishka-cms#187]
```elixir
[error] GenServer #PID<0.1831.0> terminating
** (BadArityError) #Function<0.43409555/1 in MishkaHtmlWeb.AdminCommentsLive.handle_event/3> with arity 1 called with 2 arguments ("dcf4fc71-dd0f-460b-b138-895aa0b5a37d", #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, body_color: "#a29ac3cf", comments: [], component: nil, filters: %{"count" => "30", "section_id" => "97f51152-cd9e-4c2b-88e2-3de1aa36149e"}, flash: %{}, live_action: nil, open_modal: false, page: 1, page_size: 30, page_title: "مدیریت نظرات", user_id: "8ca26675-26af-4855-a5cd-e3805eea867f"}, endpoint: MishkaHtmlWeb.Endpoint, id: "phx-FuR2Q5YYF3C5sQME", parent_pid: nil, root_pid: #PID<0.1831.0>, router: MishkaHtmlWeb.Router, transport_pid: #PID<0.1689.0>, view: MishkaHtmlWeb.AdminCommentsLive, ...>)
    (mishka_html 0.1.0) lib/mishka_html/helpers/live_crud.ex:565: MishkaHtml.Helpers.LiveCRUD.delete_item_of_list/8
    (mishka_html 0.1.0) lib/mishka_html_web/live/admin_comments_live.ex:56: MishkaHtmlWeb.AdminCommentsLive.handle_event/3
    (phoenix_live_view 0.17.7) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.3) /elixir/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.17.7) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "133", payload: %{"event" => "delete", "type" => "click", "value" => %{"id" => "dcf4fc71-dd0f-460b-b138-895aa0b5a37d"}}, ref: "140", topic: "lv:phx-FuR2Q5YYF3C5sQME"}
```

**Comment by shahryarjb** [comment]
done
